---
# - name: Update apt cache
#   action: apt update_cache=yes

- name: Update apt cache
  sudo: True
  action: command apt-get update
  when: not skip_aptget_update

- name: Install required packages.
  action: apt pkg={{item}} state=installed
  with_items: system_packages
